// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using recipeAPI.Models;

namespace recipeAPI.Migrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("recipeAPI.Models.Recipe", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("author")
                        .HasColumnType("text");

                    b.Property<string>("ingredients")
                        .HasColumnType("text");

                    b.Property<string>("instructions")
                        .HasColumnType("text");

                    b.Property<string>("pictureURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("publishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("recipe_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("RecipeArray");
                });
#pragma warning restore 612, 618
        }
    }
}
